//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aromamir
{
    using System;
    using System.Collections.Generic;
    
    public partial class NameProdyktID
    {
        public int NameID { get; set; }
        public string NameProdyct { get; set; }
    }
}
