//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aromamir
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavshik
    {
        public Nullable<int> PostavshikID { get; set; }
        public string Postavshik1 { get; set; }
    }
}
